package com.mobileprogramming.finsheet.core.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF094CB2)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF3366CC)
val onPrimaryContainerLight = Color(0xFFE7EBFF)

val secondaryLight = Color(0xFF0060AC)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF64A8FE)
val onSecondaryContainerLight = Color(0xFF003C70)

val tertiaryLight = Color(0xFF754900)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF965E00)
val onTertiaryContainerLight = Color(0xFFFFE8D1)

val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)

val backgroundLight = Color(0xFFF8F9FF)
val onBackgroundLight = Color(0xFF0B1C30)

val surfaceLight = Color(0xFFF8F9FF)
val onSurfaceLight = Color(0xFF0B1C30)
val surfaceVariantLight = Color(0xFFD3E4FE)
val onSurfaceVariantLight = Color(0xFF434653)

val outlineLight = Color(0xFF737784)
val outlineVariantLight = Color(0xFFC3C6D5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF213145)
val inverseOnSurfaceLight = Color(0xFFEAF1FF)
val inversePrimaryLight = Color(0xFFB1C5FF)
val surfaceDimLight = Color(0xFFCBDBF5)
val surfaceBrightLight = Color(0xFFF8F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF4FF)
val surfaceContainerLight = Color(0xFFE5EEFF)
val surfaceContainerHighLight = Color(0xFFDCE9FF)
val surfaceContainerHighestLight = Color(0xFFD3E4FE)
val surfaceTintLight = Color(0xFF2259BF)
val tertiaryFixedDimLight = Color(0xFFFFB95F)

// Dark Mode Colors
val primaryDark = Color(0xFFB1C5FF)
val onPrimaryDark = Color(0xFF002C72)
val primaryContainerDark = Color(0xFF00419D)
val onPrimaryContainerDark = Color(0xFFD9E2FF)
val secondaryDark = Color(0xFFA4C9FF)
val onSecondaryDark = Color(0xFF00315C)
val secondaryContainerDark = Color(0xFF004883)
val onSecondaryContainerDark = Color(0xFFD4E3FF)
val tertiaryDark = Color(0xFFFFB95F)
val onTertiaryDark = Color(0xFF472A00)
val tertiaryContainerDark = Color(0xFF653E00)
val onTertiaryContainerDark = Color(0xFFFFDDB8)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0B1C30)
val onBackgroundDark = Color(0xFFEAF1FF)
val surfaceDark = Color(0xFF0B1C30)
val onSurfaceDark = Color(0xFFEAF1FF)
val surfaceVariantDark = Color(0xFF434653)
val onSurfaceVariantDark = Color(0xFFC3C6D5)
val outlineDark = Color(0xFF8D919F)
val outlineVariantDark = Color(0xFF434653)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEAF1FF)
val inverseOnSurfaceDark = Color(0xFF213145)
val inversePrimaryDark = Color(0xFF094CB2)
val surfaceDimDark = Color(0xFF0F223A)
val surfaceBrightDark = Color(0xFF2E405A)
val surfaceContainerLowestDark = Color(0xFF051121)
val surfaceContainerLowDark = Color(0xFF0B1C30)
val surfaceContainerDark = Color(0xFF13263E)
val surfaceContainerHighDark = Color(0xFF1B314B)
val surfaceContainerHighestDark = Color(0xFF253C58)
val surfaceTintDark = Color(0xFFB1C5FF)
val tertiaryFixedDimDark = Color(0xFFFFB95F)
